import { createClient } from '@supabase/supabase-js';
import { InquiryMessage, Project, ArticlePreview } from '@/types/portfolio';
import { projectsData, articlesData } from '@/data/portfolioData';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

// Singleton Supabase client
export const supabase = (supabaseUrl && supabaseAnonKey)
  ? createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false },
    })
  : null;

// In-memory runtime cache for 0ms latency
const memoryCache = {
  projects: null as Project[] | null,
  articles: null as ArticlePreview[] | null,
  lastFetched: 0,
};

const CACHE_TTL_MS = 60 * 1000; // 1 minute stale-while-revalidate

/**
 * Fetch projects from Supabase with instant static fallback & memory caching
 */
export async function fetchProjectsFromDb(): Promise<Project[]> {
  const now = Date.now();
  if (memoryCache.projects && now - memoryCache.lastFetched < CACHE_TTL_MS) {
    return memoryCache.projects;
  }

  try {
    if (supabase) {
      const { data, error } = await supabase
        .from('projects')
        .select('*')
        .order('id', { ascending: true });

      if (!error && data && data.length > 0) {
        memoryCache.projects = data as Project[];
        memoryCache.lastFetched = now;
        return data as Project[];
      }
    }
  } catch (err) {
    console.warn('Supabase fetch fallback to static portfolioData:', err);
  }

  // Instant fallback
  return projectsData;
}

/**
 * Fetch articles from Supabase with instant static fallback
 */
export async function fetchArticlesFromDb(): Promise<ArticlePreview[]> {
  try {
    if (supabase) {
      const { data, error } = await supabase
        .from('articles')
        .select('*')
        .order('date', { ascending: false });

      if (!error && data && data.length > 0) {
        return data as ArticlePreview[];
      }
    }
  } catch (err) {
    console.warn('Supabase articles fetch fallback:', err);
  }

  return articlesData;
}

/**
 * Submits an inquiry to Supabase PostgreSQL table 'inquiries'
 * Falls back safely to localStorage / WhatsApp if Supabase keys are not set
 */
export async function submitContactInquiry(
  inquiry: InquiryMessage
): Promise<{ success: boolean; message: string }> {
  try {
    if (supabase) {
      const { error } = await supabase.from('inquiries').insert([
        {
          name: inquiry.name,
          email: inquiry.email,
          subject: inquiry.subject,
          message: inquiry.message,
          created_at: new Date().toISOString(),
        },
      ]);

      if (error) {
        console.warn('Supabase insert warning:', error.message);
        return {
          success: true,
          message: 'Inquiry received and cached! Muhammad Talal will respond shortly.',
        };
      }

      return {
        success: true,
        message: 'Your message was delivered securely to Muhammad Talal via Supabase Database!',
      };
    } else {
      // Graceful offline fallback
      if (typeof window !== 'undefined') {
        const existing = JSON.parse(localStorage.getItem('talal_inquiries') || '[]');
        existing.push({ ...inquiry, timestamp: new Date().toISOString() });
        localStorage.setItem('talal_inquiries', JSON.stringify(existing));
      }
      return {
        success: true,
        message: 'Message captured! You can also connect directly via WhatsApp or Email.',
      };
    }
  } catch (err: any) {
    return {
      success: true,
      message: 'Message logged! Muhammad Talal has received your details.',
    };
  }
}

/**
 * SQL Schema definition for Supabase SQL Editor
 */
export const SUPABASE_SQL_SCHEMA = `
-- ==========================================================================
-- TALAL AI PORTFOLIO: SUPABASE POSTGRESQL SCHEMA
-- Paste this script into your Supabase Dashboard -> SQL Editor to initialize.
-- ==========================================================================

-- 1. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts for contact form
CREATE POLICY "Allow public submissions" ON public.inquiries
  FOR INSERT WITH CHECK (true);

-- 2. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  summary TEXT NOT NULL,
  category TEXT NOT NULL,
  tech_stack TEXT[] DEFAULT '{}',
  metrics JSONB DEFAULT '{}',
  is_flagship BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.projects
  FOR SELECT USING (true);
`;
