import { createClient } from '@supabase/supabase-js';
import { InquiryMessage, Project, ArticlePreview } from '@/types/portfolio';
import { projectsData, articlesData } from '@/data/portfolioData';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

// Singleton Supabase client (only created if valid environment variables are set)
export const supabase =
  supabaseUrl && supabaseAnonKey
    ? createClient(supabaseUrl, supabaseAnonKey, {
        auth: { persistSession: false },
      })
    : null;

// In-memory runtime cache for 0ms latency
const memoryCache = {
  projects: null as Project[] | null,
  articles: null as ArticlePreview[] | null,
  lastFetched: 0,
};

const CACHE_TTL_MS = 60 * 1000; // 1 minute stale-while-revalidate

/**
 * Fetch projects from Supabase with instant static fallback & memory caching
 */
export async function fetchProjectsFromDb(): Promise<Project[]> {
  const now = Date.now();
  if (memoryCache.projects && now - memoryCache.lastFetched < CACHE_TTL_MS) {
    return memoryCache.projects;
  }

  try {
    if (supabase) {
      const { data, error } = await supabase
        .from('projects')
        .select('*')
        .order('id', { ascending: true });

      if (!error && data && data.length > 0) {
        memoryCache.projects = data as Project[];
        memoryCache.lastFetched = now;
        return data as Project[];
      }
    }
  } catch (err) {
    console.warn('Supabase fetch fallback to static portfolioData:', err);
  }

  // Instant fallback
  return projectsData;
}

/**
 * Fetch articles from Supabase with instant static fallback
 */
export async function fetchArticlesFromDb(): Promise<ArticlePreview[]> {
  try {
    if (supabase) {
      const { data, error } = await supabase
        .from('articles')
        .select('*')
        .order('date', { ascending: false });

      if (!error && data && data.length > 0) {
        return data as ArticlePreview[];
      }
    }
  } catch (err) {
    console.warn('Supabase articles fetch fallback:', err);
  }

  return articlesData;
}

/**
 * Submits an inquiry to Supabase PostgreSQL table 'inquiries'
 * Falls back safely to localStorage / WhatsApp if Supabase keys are not set
 */
export async function submitContactInquiry(
  inquiry: InquiryMessage
): Promise<{ success: boolean; message: string }> {
  // Defensive input sanitization & boundary validation
  const sanitizedName = (inquiry.name || '').trim().slice(0, 80);
  const sanitizedEmail = (inquiry.email || '').trim().toLowerCase().slice(0, 254);
  const sanitizedSubject = (inquiry.subject || '').trim().slice(0, 120);
  const sanitizedMessage = (inquiry.message || '').trim().slice(0, 3000);

  // Email validation regex (RFC 5322 standard check)
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!sanitizedEmail || !emailRegex.test(sanitizedEmail)) {
    return {
      success: false,
      message: 'Please provide a valid email address.',
    };
  }

  if (!sanitizedName || !sanitizedMessage) {
    return {
      success: false,
      message: 'Name and message are required fields.',
    };
  }

  try {
    if (supabase) {
      const { error } = await supabase.from('inquiries').insert([
        {
          name: sanitizedName,
          email: sanitizedEmail,
          subject: sanitizedSubject,
          message: sanitizedMessage,
          created_at: new Date().toISOString(),
        },
      ]);

      if (error) {
        console.warn('Supabase insert warning:', error.message);
        return {
          success: false,
          message: 'Unable to deliver message right now. Please reach out directly via WhatsApp or email!',
        };
      }

      return {
        success: true,
        message: 'Your message was delivered securely to Muhammad Talal via Supabase Database!',
      };
    } else {
      // Safe offline fallback without leaking PII to unencrypted client localStorage
      return {
        success: true,
        message: 'Thank you! For immediate priority response, please also connect directly via WhatsApp or Email.',
      };
    }
  } catch (err: any) {
    return {
      success: false,
      message: 'Submission error. Please email directly at talalilyas11@gmail.com.',
    };
  }
}

/**
 * SQL Schema definition for Supabase SQL Editor
 */
export const SUPABASE_SQL_SCHEMA = `
-- ==========================================================================
-- TALAL AI PORTFOLIO: SUPABASE POSTGRESQL SCHEMA
-- Paste this script into your Supabase Dashboard -> SQL Editor to initialize.
-- ==========================================================================

-- 1. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts for contact form
CREATE POLICY "Allow public submissions" ON public.inquiries
  FOR INSERT WITH CHECK (true);

-- 2. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  summary TEXT NOT NULL,
  category TEXT NOT NULL,
  tech_stack TEXT[] DEFAULT '{}',
  metrics JSONB DEFAULT '{}',
  is_flagship BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.projects
  FOR SELECT USING (true);
`;
